//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboundClient.InventoryServiceInbound {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventory", Namespace="http://schemas.datacontract.org/2004/07/Inventory_Prj.Service")]
    [System.SerializableAttribute()]
    public partial class Inventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Inventory_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Warehouse_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Inventory_ID {
            get {
                return this.Inventory_IDField;
            }
            set {
                if ((this.Inventory_IDField.Equals(value) != true)) {
                    this.Inventory_IDField = value;
                    this.RaisePropertyChanged("Inventory_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((this.Product_IDField.Equals(value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Quantity {
            get {
                return this.Product_QuantityField;
            }
            set {
                if ((this.Product_QuantityField.Equals(value) != true)) {
                    this.Product_QuantityField = value;
                    this.RaisePropertyChanged("Product_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Warehouse_ID {
            get {
                return this.Warehouse_IDField;
            }
            set {
                if ((this.Warehouse_IDField.Equals(value) != true)) {
                    this.Warehouse_IDField = value;
                    this.RaisePropertyChanged("Warehouse_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryServiceInbound.IInventory_Service")]
    public interface IInventory_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory_Service/Create_Inventory", ReplyAction="http://tempuri.org/IInventory_Service/Create_InventoryResponse")]
        InboundClient.InventoryServiceInbound.Create_InventoryResponse Create_Inventory(InboundClient.InventoryServiceInbound.Create_InventoryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory_Service/Create_Inventory", ReplyAction="http://tempuri.org/IInventory_Service/Create_InventoryResponse")]
        System.Threading.Tasks.Task<InboundClient.InventoryServiceInbound.Create_InventoryResponse> Create_InventoryAsync(InboundClient.InventoryServiceInbound.Create_InventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory_Service/Get_Inventories_By_Warehouse_Name", ReplyAction="http://tempuri.org/IInventory_Service/Get_Inventories_By_Warehouse_NameResponse")]
        InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameResponse Get_Inventories_By_Warehouse_Name(InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory_Service/Get_Inventories_By_Warehouse_Name", ReplyAction="http://tempuri.org/IInventory_Service/Get_Inventories_By_Warehouse_NameResponse")]
        System.Threading.Tasks.Task<InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameResponse> Get_Inventories_By_Warehouse_NameAsync(InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Inventory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Create_InventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InboundClient.InventoryServiceInbound.Inventory inventory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        public Create_InventoryRequest() {
        }
        
        public Create_InventoryRequest(InboundClient.InventoryServiceInbound.Inventory inventory, string msg) {
            this.inventory = inventory;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_InventoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Create_InventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Create_InventoryResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        public Create_InventoryResponse() {
        }
        
        public Create_InventoryResponse(bool Create_InventoryResult, string msg) {
            this.Create_InventoryResult = Create_InventoryResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Inventories_By_Warehouse_Name", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_Inventories_By_Warehouse_NameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Warehouse_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        public Get_Inventories_By_Warehouse_NameRequest() {
        }
        
        public Get_Inventories_By_Warehouse_NameRequest(string Warehouse_Name, string msg) {
            this.Warehouse_Name = Warehouse_Name;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Inventories_By_Warehouse_NameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_Inventories_By_Warehouse_NameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InboundClient.InventoryServiceInbound.Inventory[] Get_Inventories_By_Warehouse_NameResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        public Get_Inventories_By_Warehouse_NameResponse() {
        }
        
        public Get_Inventories_By_Warehouse_NameResponse(InboundClient.InventoryServiceInbound.Inventory[] Get_Inventories_By_Warehouse_NameResult, string msg) {
            this.Get_Inventories_By_Warehouse_NameResult = Get_Inventories_By_Warehouse_NameResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventory_ServiceChannel : InboundClient.InventoryServiceInbound.IInventory_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Inventory_ServiceClient : System.ServiceModel.ClientBase<InboundClient.InventoryServiceInbound.IInventory_Service>, InboundClient.InventoryServiceInbound.IInventory_Service {
        
        public Inventory_ServiceClient() {
        }
        
        public Inventory_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Inventory_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Inventory_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Inventory_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InboundClient.InventoryServiceInbound.Create_InventoryResponse InboundClient.InventoryServiceInbound.IInventory_Service.Create_Inventory(InboundClient.InventoryServiceInbound.Create_InventoryRequest request) {
            return base.Channel.Create_Inventory(request);
        }
        
        public bool Create_Inventory(InboundClient.InventoryServiceInbound.Inventory inventory, ref string msg) {
            InboundClient.InventoryServiceInbound.Create_InventoryRequest inValue = new InboundClient.InventoryServiceInbound.Create_InventoryRequest();
            inValue.inventory = inventory;
            inValue.msg = msg;
            InboundClient.InventoryServiceInbound.Create_InventoryResponse retVal = ((InboundClient.InventoryServiceInbound.IInventory_Service)(this)).Create_Inventory(inValue);
            msg = retVal.msg;
            return retVal.Create_InventoryResult;
        }
        
        public System.Threading.Tasks.Task<InboundClient.InventoryServiceInbound.Create_InventoryResponse> Create_InventoryAsync(InboundClient.InventoryServiceInbound.Create_InventoryRequest request) {
            return base.Channel.Create_InventoryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameResponse InboundClient.InventoryServiceInbound.IInventory_Service.Get_Inventories_By_Warehouse_Name(InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameRequest request) {
            return base.Channel.Get_Inventories_By_Warehouse_Name(request);
        }
        
        public InboundClient.InventoryServiceInbound.Inventory[] Get_Inventories_By_Warehouse_Name(string Warehouse_Name, ref string msg) {
            InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameRequest inValue = new InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameRequest();
            inValue.Warehouse_Name = Warehouse_Name;
            inValue.msg = msg;
            InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameResponse retVal = ((InboundClient.InventoryServiceInbound.IInventory_Service)(this)).Get_Inventories_By_Warehouse_Name(inValue);
            msg = retVal.msg;
            return retVal.Get_Inventories_By_Warehouse_NameResult;
        }
        
        public System.Threading.Tasks.Task<InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameResponse> Get_Inventories_By_Warehouse_NameAsync(InboundClient.InventoryServiceInbound.Get_Inventories_By_Warehouse_NameRequest request) {
            return base.Channel.Get_Inventories_By_Warehouse_NameAsync(request);
        }
    }
}
